services:
  # Web + API
  cam-web:
    image: nginx:alpine
    container_name: cam-web
    restart: "always"
    depends_on:
      - cam-api
    ports:
      - "80:80"
      - "888:80"
    volumes:
      - ./control/web/index.html:/usr/share/nginx/html/index.html:ro
      - ./control/web/reader.js:/usr/share/nginx/html/reader.js:ro
      - ./control/web/default.conf:/etc/nginx/conf.d/default.conf:ro

  cam-api:
    build: ./control/backend
    container_name: cam-api
    restart: unless-stopped
    env_file:
      - ./control/.env

  # HTTPS Proxy
  cam-proxy:
    image: nginx:alpine
    container_name: cam-proxy
    restart: "always"
    ports:
      - "443:443"
    volumes:
      - ./proxy/redirect.conf:/etc/nginx/conf.d/default.conf:ro
      - ./proxy/origin.crt:/etc/nginx/certs/origin.crt:ro
      - ./proxy/origin.key:/etc/nginx/certs/origin.key:ro

  # RTSP Stream
  cam-stream:
    image: bluenviron/mediamtx:latest
    container_name: cam-stream
    restart: "always"
    ports:
      - "8554:8554"
      - "8888:8888"
      - "8889:8889"
      - "8189:8189/udp"
      - "8189:8189/tcp"
    volumes:
      - ./stream/mediamtx.yml:/mediamtx.yml:ro

  cam-publisher:
    image: lscr.io/linuxserver/ffmpeg:latest
    container_name: cam-publisher
    restart: "always"
    depends_on:
      - cam-stream
    devices:
      - /dev/video0:/dev/video0
    volumes:
      - ./stream/restart.sh:/restart.sh:ro
    entrypoint: []
    command: sh /restart.sh
