services:
  # Web + API
  cam-web:
    image: nginx:alpine
    container_name: cam-web
    restart: unless-stopped
    depends_on:
      - cam-api
    ports:
      - "80:80"
      - "888:80"
    volumes:
      - ./control/web/index.html:/usr/share/nginx/html/index.html:ro
      - ./control/web/reader.js:/usr/share/nginx/html/reader.js:ro
      - ./control/web/default.conf:/etc/nginx/conf.d/default.conf:ro

  cam-api:
    build: ./control/backend
    container_name: cam-api
    restart: unless-stopped
    env_file:
      - ./control/.env

  # HTTPS Proxy
  cam-proxy:
    image: nginx:alpine
    container_name: cam-proxy
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./proxy/redirect.conf:/etc/nginx/conf.d/default.conf:ro
      - ./proxy/origin.crt:/etc/nginx/certs/origin.crt:ro
      - ./proxy/origin.key:/etc/nginx/certs/origin.key:ro

  # RTSP Stream
  cam-stream:
    image: bluenviron/mediamtx:latest
    container_name: cam-stream
    restart: unless-stopped
    ports:
      - "8554:8554"
      - "8888:8888"
      - "8889:8889"
      - "8189:8189/udp"
      - "8189:8189/tcp"
    volumes:
      - ./stream/mediamtx.yml:/mediamtx.yml:ro

  cam-publisher:
    image: lscr.io/linuxserver/ffmpeg:latest
    container_name: cam-publisher
    restart: unless-stopped
    depends_on:
      - cam-stream
    devices:
      - /dev/video0:/dev/video0
    command: >
      -hide_banner -loglevel warning
      -f v4l2 -input_format h264 -framerate 30 -video_size 1920x1080 -i /dev/video0
      -an -c:v copy
      -f rtsp -rtsp_transport tcp rtsp://cam-stream:8554/cam
